baseURL: "http://mbtamuli.github.io/"
languageCode: "en-us"
title: "mbtamuli's scratchpad"
theme:
  - github.com/adityatelange/hugo-PaperMod

caches:
  images:
    dir: :cacheDir/images

permalinks:
    blog: /:section/:slug/

# To disable, set to an extremely large value, such as 999999
pagination:
  pagerSize: 5

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
pluralizeListTitles: false

minify:
    disableXML: true
    # minifyOutput: true

languages:
    en:
        languageName: "English"
        weight: 1
        taxonomies:
          category: categories
        menu:
            main:
                - name: Blog
                  url: /blog/
                  weight: 1
                - name: Notebook
                  url: /notebook/
                  weight: 2
                - name: Categories
                  url: /categories/
                  weight: 3
                - name: About
                  url: /about/
                  weight: 4

outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
  profileMode:
    enabled: true
    subtitle: "A digital scratchpad of my thoughts and ideas."
    buttons:
      - name: Blog
        url: /blog/
      - name: Github
        url: "https://github.com/"
  socialIcons:
    - name: github
      url: "https://github.com/mbtamuli"
    - name: twitter
      url: "https://twitter.com/mbtamuli"
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  author: mbtamuli
  comments: true
  defaultTheme: auto
  ShowShareButtons: true
  ShowReadingTime: true
  disableSpecial1stPost: true
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowRssButtonInSectionTermList: true
  ShowToc: true

markup:
    goldmark:
        renderer:
            unsafe: true
